language: node_js - node
branches:
  only:
  - main
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
- nvm install node
- docker build -t tjddnjs7559/nemo_test -f ./Dockerfile.dev .
script:
- docker run -e CI=true tjddnjs7559/nemo_test npm run dev
after_success:
- echo "TEST complete, sending image to hub..."
- docker build -t tjddnjs7559/nemo_test .
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- docker push tjddnjs7559/nemo_test
