sudo: required

language: node_js - node

branches:
  only:
  - main

services:
- docker

before_install:
- ls -a
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
- ls -a
- cat .env
- nvm install node
- docker build -t tjddnjs7559/nemo_test -f ./Dockerfile.dev .
script:
- docker run -e CI=true --env-file .env tjddnjs7559/nemo_test npm run test


after_success:
- echo "TEST complete, sending image to hub..."
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- docker push tjddnjs7559/nemo_test

deploy:
- provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-northeast-2
  app: nemo_test
  env: Nemotest-env
  bucket_name: elasticbeanstalk-ap-northeast-2-291897759134
  skip_cleanup: true
  wait_until_deployed : true
  on:
    branch: main
