version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nemo_BE
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:80"
    environment:
       MYSQL_HOST: mysql 
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: ${SQUARE_WITH_ME_DB_PASSWORD}
       MYSQL_DATABASE: Square_with_me_database
       MYSQL_PORT: 3306
